### ISSUE TITLE
Cannot see processed remote video frames on clients end

### ISSUE THREAD

**Issue by Yuvraj-MirrorAR** [AgoraIO/API-Examples#285]
I'm trying to run raw video data example code https://github.com/AgoraIO/API-Examples/tree/master/windows/APIExample/APIExample/Advanced/OriginalVideo. This example code process the local video raw data but I want to perform processing on remote video raw data. I write the same gray image convert example code in the onRenderVideoFrame() function. I am getting uid and frames data but I can't see any changes in the remote participant's video. Can anyone help me with how should I render the processed frames of remote participants to other users?

![image](https://user-images.githubusercontent.com/104138685/176128042-77d2ebb8-1e2e-400f-a922-4ffbeae77154.png)

**Comment by plutoless** [comment]
@Yuvraj-MirrorAR i checked the code and that example didn't render Remote Video at all. in your case, is the problem "the video is not rendering at all" or "the remote video is rendering but without gray filter"? if it's rendering, did you change the code to render remote video yourself?

**Comment by Yuvraj-MirrorAR** [comment]
Hi, @plutoless Thanks for the reply.
Yea that example didn't render remote video. I was connecting the same room with web and android and over there I can see my local video (windows) in grey filter both on android and web but when I try to do the same for remote video, I cannot see any filter on any client end.

My Requirement is that on windows SDK I should be able to receive remote clients and perform some processing on them and present that frame to other clients. All processing of remote frames should be done on a single client in my case windows and the rest of other clients (web or android) will be the updated frames.

**Comment by plutoless** [comment]
umm... still i'm not sure abt my previous question. did you add the rendering remote code yourself? i.e. api calls like setupRemoteVideo. did you change the code to add your own view, and use setupRemoteVideo to bind the uid's video onto your view? Otherwise there's no way for you to see your remote video on your windows client.
After all the recommendation is to process the video on sender's side. Otherwise it will be pain to process all video's locally. If you want all videos to see the same gray effect, simply process the video when it's captured. Then the sent video data will already be gray filtered and receiver does not need to process it again.

**Comment by Yuvraj-MirrorAR** [comment]
@plutoless Let me try to explain to you what I am doing,
Yea I am not rendering a remote view on windows. What I want from windows is to receive the remote client's raw video data process it and send it back to SDK. So rest other clients like Web https://webdemo.agora.io/basicVideoCall/index.html and Android can see each other's processed frames they do not require to do any processing locally. 

As per docs of Raw Video data, "the SDK sends the raw video data via onCaptureVideoFrame, onPreEncodeVideoFrame, or onRenderVideoFrame" and onRenderVideoFrame is called every time when remote participant data is received. 

"After acquiring the raw data, you can process the data based on your scenario and send the processed data to the SDK via the callbacks."

Correct me I am wrong as per the docs if I have processed the frame on any remote client based on the uid, the other participants in a call now will see the processed frame by SDK they do not require to do anything locally and that's where I got stuck other participants aren't receiving the filtered frame.

**Comment by plutoless** [comment]
@Yuvraj-MirrorAR i kind of get your point but i think you have some misunderstanding here.

If you process the video frame in onRenderFrame callback, as onRenderFrame happens on your client when your client receive the video data, this will only affect your local client remote video rendering. Other clients will not be affected.
Imagine you have 3 clients in total in the channel,  A,B,C
if A process the video in onCaptureVideoFrame, the local rendering of A's video on A's client, and remote rendering of A's video on B & C's client, will all be gray filtered. B & C do not need to do anything because the video data has been processed already when it's sent out from A.
If A process the video  in onRenderVideoFrame, the local rendering of A's video on A's client, and remote rendering of B & C's video on A's client, will all be gray filtered. While B & C will show original video if they don't process the video frame, because the video data sent out from A has not been touched.

Hope i made this clear. If you want everyone's video in this channel processed, the best way is to process the video in capturing phase for every client.

**Comment by Yuvraj-MirrorAR** [comment]
Ohh, Thanks for clearing. I think I got confused about the way documentation say "send the processed data to the SDK via the callbacks."

My last question, using the later case where If A processes the video in onRenderVideoFrame, the local rendering of A's video on A's client, and remote rendering of B & C's video on A's client, will all be gray filtered. Is there any way by which B and C also see the processed frame processed by A? I don't want to do processing individually on everyone as our end goal is not just to add a grey filter.

**Comment by plutoless** [comment]
as i mentioned, then you should process A's video on A's client in onCaptureVideo, so that any remote client which receives the video stream will see the processed video frame.
The video frame path is capture -> encode -> send -> receive -> decode -> render
so if you do it before you send, then all remote video receive the processed video.

**Comment by Yuvraj-MirrorAR** [comment]
Thanks for all help!
